export const textConfig = {
  navbar: {
    appName: "AI Services Manchester",
    navItems: [
      { name: "Directory", page: "directory" },
      { name: "Manchester AI Hub", page: "manchester" },
      { name: "Contact Us", page: "contact" },
      { name: "Add Listing", page: "addListing" },
    ],
  },
  agencyCard: {
    featuredAgencyText: "Manchester's #1 AI Agency",
    primaryFocusLabel: "Primary Focus:",
    visitWebsiteButton: "Visit Website",
  },
  directoryPage: {
    title: "Manchester AI Agency Directory",
    subtitle: "Discover top AI talent and services in Manchester.",
    searchPlaceholder: "Search agencies by name, focus, or keyword...",
    searchButton: "Search",
    noResults: "No agencies found matching your search criteria.",
  },
  manchesterPage: {
    title: "Manchester: A Thriving Hub for Artificial Intelligence",
    intro: "Manchester has firmly established itself as a dynamic and leading centre for Artificial Intelligence (AI) in the United Kingdom. The city's prowess in this transformative field is substantiated by significant accolades and robust data, including being distinguished as the \"UK's most AI-ready city.\"",
    strengths: {
      heading: "Key Strengths of Manchester's AI Ecosystem:",
      items: [
        "High concentration of AI-related job opportunities.",
        "Substantial innovation funding from Innovate UK.",
        "A vibrant ecosystem of over 200 businesses specialising in AI.",
        "Home to critical initiatives like the Greater Manchester AI Foundry, empowering SMEs.",
        "Hosts AI and Data Science teams for national security organisations (GCHQ, NCSC).",
        "Strong academic backbone with The University of Manchester, an academic partner of The Alan Turing Institute.",
      ],
    },
    confluenceText: "This confluence of commercial activity, government support, and academic excellence makes Manchester a prime location for businesses seeking to leverage AI. The city's AI ecosystem represents a deeply interconnected and supportive environment, offering access to superior talent, innovative solutions, and a competitive marketplace of service providers.",
    automationConcept: `The concept of "AI Automation" is fluid, with many providers integrating automation capabilities as a core outcome of broader AI services like machine learning, data analytics, and custom AI development. This guide reflects this reality, examining automation capabilities across diverse AI offerings.`,
    outlook: {
      heading: "The Trajectory of AI in Manchester: Future Outlook",
      p1: "Manchester's current standing as a leading AI city is not temporary but a result of sustained investment, a rich talent pool, proactive business activity, and strategic public-private initiatives. The city is positioned for continued leadership and growth in the AI sector.",
      p2: "Key economic sectors—Advanced Manufacturing, Creative and Media, Digital and Technology, Financial Services, Net Zero initiatives, and Life Science & Healthcare—are poised to be significant drivers and adopters of specialised AI solutions. As AI technologies mature, their applications are expected to deepen within these areas of regional strength.",
      p3: "Government strategies, such as the UK's AI Action Plan, are likely to further catalyse development. Initiatives like the Greater Manchester AI Foundry play a crucial role in democratising access to AI and fostering innovation.",
      p4: "The trajectory suggests Manchester will not only consolidate its national AI hub status but also serve as a model for regional innovation. For businesses, this vibrant environment offers a wealth of opportunities to collaborate with cutting-edge AI providers, access skilled talent, and leverage AI for growth and transformation.",
    },
    conclusion: "Manchester's continued convergence of academic research, commercial enterprise, and supportive public policy indicates a bright and dynamic future for artificial intelligence in the region.",
  },
  contactUsPage: {
    title: "Get Listed in Our Directory",
    intro: "Are you an AI agency or service provider operating in or serving the Manchester area? We'd love to hear from you and potentially feature you in our comprehensive directory.",
    howToTouch: {
      heading: "How to Get in Touch:",
      instruction: `To be considered for inclusion in the "AI Services Manchester" directory, please send us an email with your company details, including:`,
      items: [
        "Company Name",
        "Website URL",
        "Contact Information (Phone/Email)",
        "Brief Description of your AI Services",
        "Your connection to Manchester",
      ],
      emailPrompt: "Email us at:",
      emailAddress: "info@aiservicesmanchester.co.uk",
    },
    footer: "We aim to create the most accurate and helpful resource for businesses seeking AI solutions in Manchester. We look forward to hearing from you!",
  },
  addListingPage: { // Placeholder for now
    title: "Add Your Business to the Directory",
    intro: "Complete the form below to add your AI business or service to our Manchester directory.",
    formLabels: {
        name: "Company Name",
        website: "Website URL (e.g., https://example.com)",
        phone: "Phone Number",
        email: "Contact Email",
        address: "Address (Street, City, Postcode)",
        primaryFocus: "Primary Focus/Services (comma-separated)",
        review: "Short Description/Review of Your Business (max 250 chars)",
        logoChar: "Single Character for Logo (e.g., first letter of company)",
        secretCode: "Secret Code for Submission",
    },
    submitButton: "Add My Business",
    successMessage: "Thank you! Your listing has been submitted for review.",
    failureMessage: "Submission failed. Please check your input or the secret code.",
    invalidCodeMessage: "Invalid secret code. Please try again.",
  },
  footer: {
    copyright: "© {year} AI Services Manchester. All rights reserved.",
    tagline: "Your guide to AI innovation in Manchester.",
  },
}; 